name: Terraform Azure Pipeline

on:
  push:
    branches:
      - featurebranch2

jobs:
  terraform:
    runs-on: ubuntu-latest

    steps:

      # 1. Checkout code
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup Terraform
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      # 3. Azure Login - Hard Coded Service Principal
      - name: Azure Login
        uses: azure/login@v2
        with:
          creds: |
            {
              "clientId": "de73c7ea-b550-4746-8010-221113c74a7a",
              "clientSecret": "hSo8Q~ncFgxrwl~-bazJVHmwRewIHaeNjRbb1bqC",
              "tenantId": "8968e7c0-454e-4762-8227-5070cecb405c",
              "subscriptionId": "20f0748e-1dfc-4085-9be6-07b106f015ed"
            }

      # 4. Verify Azure Login
      - name: Check Azure Login
        run: |
          az account show

      # 5. Terraform Init
      - name: Terraform Init
        run: terraform init

      # 6. Terraform Validate
      - name: Terraform Validate
        run: terraform validate

      # 7. Terraform Plan
      - name: Terraform Plan
        run: terraform plan

      # 8. Terraform Apply
      # - name: Terraform Apply
      #   run: terraform apply -auto-approve
